import { supabase, supabaseAdmin } from '../config/supabase.js';

/**
 * POST /api/registrations/direct
 * Direct Student Registration: Auto-creates account if guest, handles GPay screenshot,
 * generates ticket, and returns credentials to display on UI.
 */
export async function registerDirect(req, res) {
  try {
    const {
      event_id,
      full_name,
      email,
      roll_number,
      department,
      year_of_study,
      phone,
      payment_mode = 'free',
      payment_proof_url = null,
    } = req.body;

    if (!event_id || !full_name || !email || !roll_number || !department || !year_of_study) {
      return res.status(400).json({
        success: false,
        error: 'Please fill in all required registration fields.',
      });
    }

    // 1. Fetch and validate event
    const { data: event, error: eventError } = await supabaseAdmin
      .from('events')
      .select('*')
      .eq('id', event_id)
      .single();

    if (eventError || !event) {
      return res.status(404).json({ success: false, error: 'Event not found.' });
    }

    if (event.status !== 'published') {
      return res.status(400).json({ success: false, error: 'Registrations are closed for this event.' });
    }

    if (new Date() > new Date(event.registration_deadline)) {
      return res.status(400).json({ success: false, error: 'Registration deadline has passed.' });
    }

    // Check capacity
    const { count: currentRegistrations } = await supabaseAdmin
      .from('registrations')
      .select('*', { count: 'exact', head: true })
      .eq('event_id', event_id)
      .neq('status', 'cancelled');

    if ((currentRegistrations || 0) >= event.capacity) {
      return res.status(400).json({ success: false, error: 'Event has reached maximum capacity.' });
    }

    let studentId = req.user?.id;
    let isNewUser = false;
    let autoGeneratedPassword = null;

    // 2. If student is not logged in, check existing profile or auto-create account
    if (!studentId) {
      const trimmedEmail = email.trim().toLowerCase();
      const trimmedRoll = roll_number.trim();

      // Check if profile exists by email
      const { data: existingProfile } = await supabaseAdmin
        .from('profiles')
        .select('id, email, role, student_id')
        .eq('email', trimmedEmail)
        .maybeSingle();

      if (existingProfile) {
        studentId = existingProfile.id;
      } else {
        // Auto-generate password: KSRCE@<roll_number> (e.g. KSRCE@73152413003)
        autoGeneratedPassword = `KSRCE@${trimmedRoll}`;
        isNewUser = true;

        // Create Auth User via Supabase Admin API
        const { data: newUser, error: createError } = await supabaseAdmin.auth.admin.createUser({
          email: trimmedEmail,
          password: autoGeneratedPassword,
          email_confirm: true,
          user_metadata: {
            role: 'student',
            full_name: full_name.trim(),
            student_id: `CCS-${new Date().getFullYear()}-${Math.floor(10000 + Math.random() * 90000)}`,
          },
        });

        if (createError || !newUser.user) {
          console.error('[registerDirect] Auth creation error:', createError);
          return res.status(400).json({
            success: false,
            error: createError?.message || 'Could not auto-create student account.',
          });
        }

        studentId = newUser.user.id;

        // Insert Student Academic Profile
        await supabaseAdmin
          .from('student_profiles')
          .insert({
            user_id: studentId,
            full_name: full_name.trim(),
            roll_number: trimmedRoll,
            department: department.trim(),
            year_of_study: parseInt(year_of_study, 10),
            phone: phone ? phone.trim() : null,
          });
      }
    }

    // 3. Check for duplicate registration
    const { data: existingReg } = await supabaseAdmin
      .from('registrations')
      .select('id, ticket_code, status')
      .eq('event_id', event_id)
      .eq('student_id', studentId)
      .neq('status', 'cancelled')
      .maybeSingle();

    if (existingReg) {
      return res.status(400).json({
        success: false,
        error: 'You are already registered for this event.',
        registration_id: existingReg.id,
        ticket_code: existingReg.ticket_code,
      });
    }

    // 4. Determine Payment Status
    const isPaid = event.is_paid || (event.entry_fee && event.entry_fee > 0);
    const paymentStatus = isPaid ? 'pending_verification' : 'free';
    const actualPaymentMode = isPaid ? (payment_mode || 'gpay_upi') : 'free';

    // 5. Generate Ticket Code
    const ticketCode = `CC-${event_id.slice(0, 4).toUpperCase()}-${Math.random()
      .toString(36)
      .substring(2, 10)
      .toUpperCase()}`;

    // 6. Insert Registration
    const { data: newReg, error: regError } = await supabaseAdmin
      .from('registrations')
      .insert({
        event_id,
        student_id: studentId,
        ticket_code: ticketCode,
        status: 'registered',
        payment_mode: actualPaymentMode,
        payment_proof_url: payment_proof_url || null,
        payment_status: paymentStatus,
        registered_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (regError || !newReg) {
      console.error('[registerDirect] Registration insert error:', regError);
      return res.status(400).json({
        success: false,
        error: regError?.message || 'Failed to complete registration.',
      });
    }

    // 7. Queue confirmation email to student
    await supabaseAdmin
      .from('email_notifications')
      .insert({
        registration_id: newReg.id,
        event_id,
        recipient_email: email.trim().toLowerCase(),
        recipient_name: full_name.trim(),
        recipient_type: 'student',
        notification_type: 'registration_confirmation',
        subject: `Your Registration Pass for ${event.title}`,
        template_data: {
          ticket_code: ticketCode,
          event_title: event.title,
          venue: event.venue,
          event_start: event.event_start,
          student_name: full_name.trim(),
          scan_url: '/attendance/scan',
          ticket_url: `/ticket/${newReg.id}`,
        },
        status: 'pending',
      });

    return res.status(201).json({
      success: true,
      message: 'Registration confirmed successfully!',
      registration_id: newReg.id,
      ticket_code: ticketCode,
      is_new_user: isNewUser,
      user_credentials: isNewUser
        ? {
            email: email.trim().toLowerCase(),
            password: autoGeneratedPassword,
          }
        : null,
    });
  } catch (err) {
    console.error('[registerDirect Error]:', err);
    return res.status(500).json({
      success: false,
      error: 'Registration failed due to server error.',
    });
  }
}

/**
 * POST /api/registrations (Atomic Student Registration for logged-in users)
 */
export async function registerForEvent(req, res) {
  try {
    const studentId = req.user.id;
    const { event_id, payment_mode = 'free', payment_proof_url = null } = req.body;

    if (!event_id) {
      return res.status(400).json({ success: false, error: 'Event ID is required.' });
    }

    const ticketCode = `CC-${event_id.slice(0, 4).toUpperCase()}-${Math.random()
      .toString(36)
      .substring(2, 10)
      .toUpperCase()}`;

    const { data: result, error: rpcError } = await supabaseAdmin.rpc(
      'register_student_for_event',
      {
        p_event_id: event_id,
        p_student_id: studentId,
        p_ticket_code: ticketCode,
      }
    );

    if (rpcError) {
      return res.status(400).json({ success: false, error: rpcError.message });
    }

    if (!result.success) {
      return res.status(400).json({ success: false, error: result.error });
    }

    // Update payment proof if provided
    if (payment_proof_url) {
      await supabaseAdmin
        .from('registrations')
        .update({
          payment_proof_url,
          payment_mode,
          payment_status: 'pending_verification',
        })
        .eq('id', result.registration_id);
    }

    return res.status(201).json({
      success: true,
      message: 'Registration confirmed!',
      registration_id: result.registration_id,
      ticket_code: result.ticket_code,
    });
  } catch (err) {
    console.error('[registerForEvent Error]:', err);
    return res.status(500).json({
      success: false,
      error: 'Registration failed due to server error.',
    });
  }
}

/**
 * GET /api/registrations/my (Get Logged-in Student Registrations)
 */
export async function getMyRegistrations(req, res) {
  try {
    const studentId = req.user.id;

    const { data: registrations, error } = await supabaseAdmin
      .from('registrations')
      .select(`
        id, event_id, student_id, ticket_code, qr_image_url, status,
        payment_mode, payment_proof_url, payment_status, registered_at,
        events (
          id, title, category, event_start, event_end, venue, banner_url, organizer_club, entry_fee, is_paid, status
        )
      `)
      .eq('student_id', studentId)
      .order('registered_at', { ascending: false });

    if (error) {
      return res.status(400).json({ success: false, error: error.message });
    }

    const formatted = (registrations || []).map(r => ({
      ...r,
      event: r.events,
    }));

    return res.status(200).json({
      success: true,
      count: formatted.length,
      data: formatted,
    });
  } catch (err) {
    console.error('[getMyRegistrations Error]:', err);
    return res.status(500).json({
      success: false,
      error: 'Failed to fetch your registrations.',
    });
  }
}

/**
 * GET /api/registrations/:id (Get Single Ticket by ID)
 */
export async function getRegistrationById(req, res) {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    const { data: registration, error } = await supabaseAdmin
      .from('registrations')
      .select(`
        id, event_id, student_id, ticket_code, qr_image_url, status,
        payment_mode, payment_proof_url, payment_status, registered_at,
        events (
          id, title, category, event_start, event_end, venue, banner_url, organizer_club, entry_fee, is_paid, capacity, status
        )
      `)
      .eq('id', id)
      .single();

    if (error || !registration) {
      return res.status(404).json({ success: false, error: 'Ticket not found.' });
    }

    if (registration.student_id !== userId && req.profile.role === 'student') {
      return res.status(403).json({
        success: false,
        error: 'You do not have permission to view this ticket.',
      });
    }

    return res.status(200).json({
      success: true,
      data: {
        ...registration,
        event: registration.events,
      },
    });
  } catch (err) {
    console.error('[getRegistrationById Error]:', err);
    return res.status(500).json({
      success: false,
      error: 'Failed to fetch ticket details.',
    });
  }
}

/**
 * POST /api/registrations/:id/cancel (Cancel Registration)
 */
export async function cancelRegistration(req, res) {
  try {
    const { id } = req.params;
    const studentId = req.user.id;

    const { data: updated, error } = await supabaseAdmin
      .from('registrations')
      .update({ status: 'cancelled' })
      .eq('id', id)
      .eq('student_id', studentId)
      .select()
      .single();

    if (error || !updated) {
      return res.status(400).json({
        success: false,
        error: 'Unable to cancel registration.',
      });
    }

    return res.status(200).json({
      success: true,
      message: 'Registration cancelled successfully.',
    });
  } catch (err) {
    console.error('[cancelRegistration Error]:', err);
    return res.status(500).json({
      success: false,
      error: 'Failed to cancel registration.',
    });
  }
}
